/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author dam211
 */
public class Ventana_gestion extends javax.swing.JDialog {

    /**
     * Creates new form Ventana_gestion
     */
    public Ventana_gestion() {
        super();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        panelDatosCliente = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_nif = new javax.swing.JLabel();
        txt_nif = new javax.swing.JTextField();
        panelDatosVehiculo = new javax.swing.JPanel();
        lbl_matricula = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        lbl_modelo = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        lbl_tipo = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        panelDatosReparacion = new javax.swing.JPanel();
        separaServicio = new javax.swing.JSeparator();
        separaFechaIni = new javax.swing.JSeparator();
        separaMecanico = new javax.swing.JSeparator();
        separaFechaFin = new javax.swing.JSeparator();
        separaPrecio = new javax.swing.JSeparator();
        separaTiempoTotal = new javax.swing.JSeparator();
        lbl_tiempoTotal = new javax.swing.JLabel();
        lbl_mecanico = new javax.swing.JLabel();
        comboMecanico = new javax.swing.JComboBox<>();
        lbl_servicio = new javax.swing.JLabel();
        comboServicio = new javax.swing.JComboBox<>();
        lbl_fechaIni = new javax.swing.JLabel();
        lbl_FechaIni = new javax.swing.JLabel();
        lbl_fechaFin = new javax.swing.JLabel();
        spinFechaIni = new javax.swing.JSpinner();
        spinFechaFin = new javax.swing.JSpinner();
        precioTotal = new javax.swing.JLabel();
        tiempoTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_servicios = new javax.swing.JTable();
        botonAñadir = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        panelTransparente = new javax.swing.JPanel();
        img_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 24, 353, 50));

        panelInferior.setBackground(new java.awt.Color(204, 204, 255));
        panelInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatosCliente.setBackground(new java.awt.Color(221, 255, 221));
        panelDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelDatosCliente.setPreferredSize(new java.awt.Dimension(240, 128));

        lbl_nombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombre.setLabelFor(txt_nombre);
        lbl_nombre.setText("Nombre:");

        txt_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre.setToolTipText("Introduce el nombre del cliente");
        txt_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nombre.setNextFocusableComponent(txt_nif);

        lbl_nif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_nif.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nif.setLabelFor(txt_nif);
        lbl_nif.setText("NIF:");

        txt_nif.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_nif.setForeground(new java.awt.Color(0, 0, 0));
        txt_nif.setToolTipText("Introduce el nif del cliente");
        txt_nif.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nif.setNextFocusableComponent(txt_matricula);

        javax.swing.GroupLayout panelDatosClienteLayout = new javax.swing.GroupLayout(panelDatosCliente);
        panelDatosCliente.setLayout(panelDatosClienteLayout);
        panelDatosClienteLayout.setHorizontalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(lbl_nif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nif, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txt_nombre))
                .addContainerGap())
        );
        panelDatosClienteLayout.setVerticalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelInferior.add(panelDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 140));

        panelDatosVehiculo.setBackground(new java.awt.Color(221, 255, 221));
        panelDatosVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos vehiculos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelDatosVehiculo.setPreferredSize(new java.awt.Dimension(237, 128));
        panelDatosVehiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_matricula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_matricula.setForeground(new java.awt.Color(0, 0, 0));
        lbl_matricula.setLabelFor(txt_matricula);
        lbl_matricula.setText("Matricula:");
        panelDatosVehiculo.add(lbl_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 25, 76, 37));

        txt_matricula.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_matricula.setForeground(new java.awt.Color(0, 0, 0));
        txt_matricula.setToolTipText("Introduce la matricula del vehiculo");
        txt_matricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_matricula.setNextFocusableComponent(txt_modelo);
        panelDatosVehiculo.add(txt_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 25, 136, 37));

        lbl_modelo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_modelo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_modelo.setLabelFor(txt_modelo);
        lbl_modelo.setText("Modelo:");
        panelDatosVehiculo.add(lbl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 80, 76, 37));

        txt_modelo.setEditable(false);
        txt_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(0, 0, 0));
        txt_modelo.setToolTipText("Introduce el modelo del vehiculo");
        txt_modelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_modelo.setNextFocusableComponent(comboMecanico);
        panelDatosVehiculo.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 80, 136, 37));

        lbl_tipo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_tipo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tipo.setLabelFor(txt_modelo);
        lbl_tipo.setText("Tipo:");
        panelDatosVehiculo.add(lbl_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 135, 76, 37));

        comboTipo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboTipo.setForeground(new java.awt.Color(0, 0, 0));
        comboTipo.setToolTipText("Selecciona el mecanico encargado de la reparacion");
        comboTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatosVehiculo.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 135, 136, 37));

        panelInferior.add(panelDatosVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 190));

        panelDatosReparacion.setBackground(new java.awt.Color(221, 255, 221));
        panelDatosReparacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos reparaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelDatosReparacion.setPreferredSize(new java.awt.Dimension(237, 128));
        panelDatosReparacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separaServicio.setBackground(new java.awt.Color(0, 0, 0));
        separaServicio.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosReparacion.add(separaServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 55, 160, 12));

        separaFechaIni.setBackground(new java.awt.Color(0, 0, 0));
        separaFechaIni.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosReparacion.add(separaFechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 215, 140, 12));

        separaMecanico.setBackground(new java.awt.Color(0, 0, 0));
        separaMecanico.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosReparacion.add(separaMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 55, 140, 12));

        separaFechaFin.setBackground(new java.awt.Color(0, 0, 0));
        separaFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosReparacion.add(separaFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 215, 140, 12));

        separaPrecio.setBackground(new java.awt.Color(0, 0, 0));
        separaPrecio.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosReparacion.add(separaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 135, 140, 12));

        separaTiempoTotal.setBackground(new java.awt.Color(0, 0, 0));
        separaTiempoTotal.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosReparacion.add(separaTiempoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 295, 139, 12));

        lbl_tiempoTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_tiempoTotal.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tiempoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tiempoTotal.setLabelFor(comboMecanico);
        lbl_tiempoTotal.setText("Tiempo Total");
        panelDatosReparacion.add(lbl_tiempoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, 37));

        lbl_mecanico.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_mecanico.setForeground(new java.awt.Color(0, 0, 0));
        lbl_mecanico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mecanico.setLabelFor(comboMecanico);
        lbl_mecanico.setText("Mecanico");
        panelDatosReparacion.add(lbl_mecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 37));

        comboMecanico.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboMecanico.setForeground(new java.awt.Color(0, 0, 0));
        comboMecanico.setToolTipText("Selecciona el mecanico encargado de la reparacion");
        comboMecanico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatosReparacion.add(comboMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 34));

        lbl_servicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_servicio.setForeground(new java.awt.Color(0, 0, 0));
        lbl_servicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_servicio.setLabelFor(comboMecanico);
        lbl_servicio.setText("Servicio");
        panelDatosReparacion.add(lbl_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 160, 37));

        comboServicio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboServicio.setForeground(new java.awt.Color(0, 0, 0));
        comboServicio.setToolTipText("Selecciona el mecanico encargado de la reparacion");
        comboServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatosReparacion.add(comboServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 160, 34));

        lbl_fechaIni.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_fechaIni.setForeground(new java.awt.Color(0, 0, 0));
        lbl_fechaIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fechaIni.setLabelFor(comboMecanico);
        lbl_fechaIni.setText("Fecha de inicio");
        panelDatosReparacion.add(lbl_fechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, 37));

        lbl_FechaIni.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_FechaIni.setForeground(new java.awt.Color(0, 0, 0));
        lbl_FechaIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_FechaIni.setLabelFor(comboMecanico);
        lbl_FechaIni.setText("Precio Total");
        panelDatosReparacion.add(lbl_FechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 37));

        lbl_fechaFin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_fechaFin.setForeground(new java.awt.Color(0, 0, 0));
        lbl_fechaFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fechaFin.setLabelFor(comboMecanico);
        lbl_fechaFin.setText("Fecha de fin");
        panelDatosReparacion.add(lbl_fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 140, 37));

        spinFechaIni.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        spinFechaIni.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_WEEK));
        spinFechaIni.setToolTipText("Introduce la fecha y hora del inicio de la reparacion");
        spinFechaIni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spinFechaIni.setNextFocusableComponent(spinFechaFin);
        panelDatosReparacion.add(spinFechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, 34));

        spinFechaFin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        spinFechaFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_WEEK));
        spinFechaFin.setToolTipText("Introduce la fecha y hora del fin de la reparacion");
        spinFechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        spinFechaFin.setNextFocusableComponent(botonGuardar);
        panelDatosReparacion.add(spinFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 140, 34));

        precioTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        precioTotal.setForeground(new java.awt.Color(0, 0, 0));
        precioTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelDatosReparacion.add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 34));

        tiempoTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tiempoTotal.setForeground(new java.awt.Color(0, 0, 0));
        tiempoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelDatosReparacion.add(tiempoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 140, 34));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla_servicios.setForeground(new java.awt.Color(0, 0, 0));
        tabla_servicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_servicios);

        panelDatosReparacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 230, 140));

        botonAñadir.setBackground(new java.awt.Color(51, 255, 51));
        botonAñadir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botonAñadir.setForeground(new java.awt.Color(0, 0, 0));
        botonAñadir.setText("Añadir");
        botonAñadir.setToolTipText("Pulsa para añadir los servicios a la tabla");
        botonAñadir.setNextFocusableComponent(botonCancelar);
        panelDatosReparacion.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 90, 34));

        botonEliminar.setBackground(new java.awt.Color(255, 51, 51));
        botonEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setText("Eliminar");
        botonEliminar.setToolTipText("Pulsa para eliminar los servicios seleccionados de la tabla");
        botonEliminar.setNextFocusableComponent(botonCancelar);
        panelDatosReparacion.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 90, 34));

        panelInferior.add(panelDatosReparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 700, 370));

        botonGuardar.setBackground(new java.awt.Color(51, 255, 51));
        botonGuardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("Guardar");
        botonGuardar.setToolTipText("Pulsa para guardar los datos");
        botonGuardar.setNextFocusableComponent(botonCancelar);
        panelInferior.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 143, 44));

        botonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        botonCancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setText("Cancelar");
        botonCancelar.setToolTipText("Pulsa para cancelar los datos y volver atras.");
        botonCancelar.setNextFocusableComponent(txt_nombre);
        panelInferior.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 530, 144, 44));

        panelTransparente.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelTransparenteLayout = new javax.swing.GroupLayout(panelTransparente);
        panelTransparente.setLayout(panelTransparenteLayout);
        panelTransparenteLayout.setHorizontalGroup(
            panelTransparenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelTransparenteLayout.setVerticalGroup(
            panelTransparenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panelInferior.add(panelTransparente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        img_fondo.setBackground(new java.awt.Color(204, 204, 204));
        img_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taller-motos.jpg"))); // NOI18N
        panelInferior.add(img_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(panelInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAñadir;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JButton botonGuardar;
    public javax.swing.JComboBox<String> comboMecanico;
    public javax.swing.JComboBox<String> comboServicio;
    public javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel img_fondo;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_FechaIni;
    private javax.swing.JLabel lbl_fechaFin;
    private javax.swing.JLabel lbl_fechaIni;
    private javax.swing.JLabel lbl_matricula;
    private javax.swing.JLabel lbl_mecanico;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_nif;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_servicio;
    private javax.swing.JLabel lbl_tiempoTotal;
    private javax.swing.JLabel lbl_tipo;
    public javax.swing.JPanel panelDatosCliente;
    public javax.swing.JPanel panelDatosReparacion;
    public javax.swing.JPanel panelDatosVehiculo;
    public javax.swing.JPanel panelInferior;
    public javax.swing.JPanel panelTransparente;
    public javax.swing.JLabel precioTotal;
    private javax.swing.JSeparator separaFechaFin;
    private javax.swing.JSeparator separaFechaIni;
    private javax.swing.JSeparator separaMecanico;
    private javax.swing.JSeparator separaPrecio;
    private javax.swing.JSeparator separaServicio;
    private javax.swing.JSeparator separaTiempoTotal;
    public javax.swing.JSpinner spinFechaFin;
    public javax.swing.JSpinner spinFechaIni;
    public javax.swing.JTable tabla_servicios;
    public javax.swing.JLabel tiempoTotal;
    public javax.swing.JLabel titulo;
    public javax.swing.JTextField txt_matricula;
    public javax.swing.JTextField txt_modelo;
    public javax.swing.JTextField txt_nif;
    public javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
