/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author dam211
 */
public class Ventana_principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_principal
     */
    public Ventana_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Fondo = new javax.swing.JPanel();
        panelBorde = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVehiculos = new javax.swing.JMenu();
        botonMenuRegistrar = new javax.swing.JMenuItem();
        botonMenuBuscar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        botonMenuV1 = new javax.swing.JMenuItem();
        botonMenuV2 = new javax.swing.JMenuItem();
        botonMenuAcerca = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taller_AGL");

        Fondo.setBackground(new java.awt.Color(177, 204, 139));

        panelBorde.setBackground(new java.awt.Color(177, 204, 139));
        panelBorde.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gestion de taller", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        panelBorde.setForeground(new java.awt.Color(0, 0, 0));
        panelBorde.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        botonBuscar.setBackground(new java.awt.Color(158, 112, 34));
        botonBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscar.setText("Buscar");
        botonBuscar.setToolTipText("Pulsar para abrir el menu de bicicletas");

        botonRegistrar.setBackground(new java.awt.Color(0, 211, 224));
        botonRegistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setToolTipText("Pulsar para abrir el menu de motocicletas");

        javax.swing.GroupLayout panelBordeLayout = new javax.swing.GroupLayout(panelBorde);
        panelBorde.setLayout(panelBordeLayout);
        panelBordeLayout.setHorizontalGroup(
            panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBordeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        panelBordeLayout.setVerticalGroup(
            panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBordeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panelBorde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(panelBorde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuVehiculos.setText("Vehiculos");
        menuVehiculos.setToolTipText("Abrir las opciones del taller");

        botonMenuRegistrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK));
        botonMenuRegistrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonMenuRegistrar.setText("Registrar");
        botonMenuRegistrar.setToolTipText("Ir al panel de motocicletas");
        menuVehiculos.add(botonMenuRegistrar);

        botonMenuBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        botonMenuBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonMenuBuscar.setText("Buscar");
        botonMenuBuscar.setToolTipText("Ir al panel de bicicletas");
        botonMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuBuscarActionPerformed(evt);
            }
        });
        menuVehiculos.add(botonMenuBuscar);

        jMenuBar1.add(menuVehiculos);

        menuAyuda.setText("Ayuda");
        menuAyuda.setToolTipText("Abrir el menu desplegable de ayuda.");

        jMenu2.setText("Versiones");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        botonMenuV1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonMenuV1.setText("V 1.1");
        botonMenuV1.setToolTipText("Informacion de la V 1.1");
        jMenu2.add(botonMenuV1);

        botonMenuV2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonMenuV2.setText("V 1.2");
        botonMenuV2.setToolTipText("Informacion de la V 1.2");
        jMenu2.add(botonMenuV2);

        menuAyuda.add(jMenu2);

        botonMenuAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        botonMenuAcerca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonMenuAcerca.setText("Acerca de...");
        botonMenuAcerca.setToolTipText("Información sobre la aplicación");
        menuAyuda.add(botonMenuAcerca);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMenuBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    public javax.swing.JButton botonBuscar;
    public javax.swing.JMenuItem botonMenuAcerca;
    public javax.swing.JMenuItem botonMenuBuscar;
    public javax.swing.JMenuItem botonMenuRegistrar;
    public javax.swing.JMenuItem botonMenuV1;
    public javax.swing.JMenuItem botonMenuV2;
    public javax.swing.JButton botonRegistrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuVehiculos;
    public javax.swing.JPanel panelBorde;
    // End of variables declaration//GEN-END:variables
}
